classDiagram
    class Book {
        +str title
        +str author
        +bool state
        +mark_as_available()
        +mark_as_unavailable()
    }

    class User {
        +str name
        +str email
    }

    class Loan {
        +str start_date
        +str end_date
        +close_loan()
    }

    class Library {
        +add_book()
        +register_user()
        +create_loan()
    }

    Library "1" o-- "*" Book
    Library "1" o-- "*" User
    Library "1" -- "*" Loan
    Loan "*" -- "1" Book
    Loan "*" -- "1" User
